version: "3"

services:
  backend:
    build:
      context: ./backend
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_HOST=postgres"
      - "PORT=3005"
    networks:
      - postgres_app-tier
    ports:
      - 8080:8080
    container_name: backend
    expose:
      - 8080

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    expose:
      - 3005
    ports:
      - 3005:3005
    environment:
      - BACKEND_API_URL=backend
    depends_on:
      - "backend"
    links:
      - "backend:backend"

networks:
  postgres_app-tier:
    external: true
