version: "3.9"
services:
  consumer:
    build: .
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_HOST=postgres"
    networks:
      - postgres_app-tier
    ports:
      - 3000:3000
networks:
  postgres_app-tier:
    external: true
