version: "3"

services:
  backend:
    build:
      context: .
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_HOST=postgres"
      - "PORT=3001"
    networks:
      - postgres_app-tier
      - app-tier
    ports:
      - 3001:3001
    container_name: backend
    expose:
      - 8080

networks:
  app-tier:
    driver: bridge

  postgres_app-tier:
    external: true
