version: '3.4'

services:
  db:
    image: postgres:14
    container_name: eyyg_postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
  python:
    container_name: eyyg_python
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - db